### ISSUE TITLE
add this base model in model section

### ISSUE THREAD

**Issue by umefarooq** [codeigniter-id/awesome-codeigniter#24]
please add this base model to model list its best base model with lots of features, before and after actions, form validation, database relation ships.

https://github.com/jamierumbelow/codeigniter-base-model

**Comment by suhindra** [comment]
already on the list [CRUD](https://github.com/codeigniter-id/awesome-codeigniter#crud)

**Comment by umefarooq** [comment]
sorry for that after posting this comment i checked it was there.
